const PAIS = 0;
const CODI = 1;
const CIUTAT = 2;
const TIPUS = 3;
const NOM = 4;
const DIRECCIO = 5;
const LATITUD = 6;
const LONGITUD = 7;
const HORARIS = 8;
const PREU = 9;
const DESCRIPCIO = 10;
const PUNTUACIO = 11;
const MONEDA = 12;

export { PAIS,CODI,CIUTAT,TIPUS,NOM,DIRECCIO,LATITUD,LONGITUD,HORARIS,PREU,DESCRIPCIO,PUNTUACIO,MONEDA};